### ISSUE TITLE
todo : 

### ISSUE THREAD

**Issue by plankatron** [circusautomatic/ctulhoid#1]
1. test out dynamixel torque settings 
2. implement planning code for gymbal movement : 
3. make ip settable in arduino sketch

**Comment by fgcapo** [comment]
http://support.robotis.com/en/product/dynamixel/ax_series/dxl_ax_actuator.htm

See Max Torque, Present Load, Present Speed. Torque Enable flag just seems to disable the motor.

**Comment by plankatron** [comment]
lol fun times..

**Comment by fgcapo** [comment]
Increasing COMPLIANCE_SLOPE reduces jerkiness during motion but increases the margin of error of the final position.

COMPLIANCE_MARGIN seems already set to smallest value.

**Comment by fgcapo** [comment]
Max Torque defaults to maximum value.

**Comment by fgcapo** [comment]
Gimbal movement is shelved for now.
